services:
    bpaulin.setupezcontenttype.import:
        class: Bpaulin\SetupEzContentTypeBundle\Service\Import
        calls:
            - [ setContainer,[ @service_container ] ]
    bpaulin.setupezcontenttype.field_factory:
        class: Bpaulin\SetupEzContentTypeBundle\Service\FieldFactory
        calls:
            - [ setContainer,[ @service_container ] ]
